apollographql/apollo

design/high-level-reactivity.md

Add a link to LearnGraphQL. Not sure exactly where to put it.

Add LearnGraphQL link

---

css/layout.less

keyboard focus: website doesn't scroll when pressing spacebar #25

spacebar issue fixed

---

css/layout.less

This should fix the spacebar issue. I can't see why that position absolute was added there but removing it does not break anything.

spacebar issue fix

---

code-of-conduct.md

Add Code of Conduct to meta repo

---

meetings/contributors-weekly/12-09-17.md

Notes from Sep 12 meeting

---

meetings/contributors-weekly/19-09-17.md

Couple of topics

---

meetings/contributors-weekly/19-09-17.md

Include some topics

---

docs/source/index.md

Simplified and pared down language on the Apollo index page

---

docs/package.json
renovate.json

In the same nature as apollographql/apollo-server@9ab2765.

Move Docs Renovate configuration into top-level `renovate.json`.

---

docs/source/guides/schema-design.md
docs/source/guides/versioning.md

This PR targets #155 and hopefully addresses @stubailo's (excellent) [feedback](https://github.com/apollographql/apollo/pull/155#pullrequestreview-124634832).  Specifically, these:
* https://github.com/apollographql/apollo/pull/155#discussion_r191957939
* https://github.com/apollographql/apollo/pull/155#discussion_r191958434
Questionably addressed is:
* https://github.com/apollographql/apollo/pull/155#discussion_r191959082
And not addressed, yet:
* https://github.com/apollographql/apollo/pull/155#discussion_r191959210

Address `schema-design.md` feedback.

---

docs/source/guides/access-control.md

"we probably don’t just anyone"

Fix typo in access-control.md

---

docs/source/index.md

Change link to Apollo Server 2

---

docs/source/guides/access-control.md

Add more info on auth via schema directives

---

docs/source/guides/file-uploads.md

Add Blob example

---

docs/source/guides/file-uploads.md

Update File Upload Docs

---

docs/source/guides/performance.md

Fixed typo in variable name

---

docs/source/guides/access-control.md

Apollo Server 2 no longer in beta

---

docs/source/fundamentals/platform.md
docs/source/fundamentals/tips.md

Guides Clean Up & Buttering 

---

docs/source/resources/graphql-glossary.md

Remove useless backticks

---

docs/source/resources/faq.md

Noticed some link typos, fixed them.

Updated faq

---

docs/source/guides/performance.md

'allows implements' -> 'implements'

docs: Fix minor grammar issue in performance docs

---

docs/source/tutorial/data-source.md

Add content for data sources section

---

docs/source/tutorial/client.md

Connect your graph API to a client

---

docs/source/tutorial/client.md
docs/source/tutorial/local-state.md
docs/source/tutorial/mutations.md
docs/source/tutorial/queries.md

Add Content For Fetch Data With Queries #219

---

docs/source/tutorial/production.md

Add note about npx

---

docs/source/tutorial/introduction.md

Add links to devtools and apollo vscode

---

docs/_config.yml

Remove unimplemented doc links from sidebar

---

docs/_config.yml
docs/package-lock.json
docs/package.json
docs/source/platform/editor-plugins.md
docs/source/platform/operation-registry.md
docs/source/platform/schema-registry.md
docs/source/platform/schema-validation.md
docs/source/resources/apollo-config.md

@peggyrayzis @daniman this is a first pass at updated docs for the schema registry, editor integrations, and the apollo config. I'm going to go ahead and merge them since we have nothing up yet, but can y'all review and lets make these better this week?

update docs on schema publishing and CLI + config

---

docs/_config.yml

Set up redirects for guides to new platform links

---

docs/_config.yml
docs/public/_redirects

Implement server redirects 

---

docs/source/platform/schema-validation.md
docs/source/tutorial/production.md

schema: -> service:

---

docs/package-lock.json
docs/package.json

Reverts apollographql/apollo#269

Revert "Update dependency hexo-renderer-less to v1"

---

docs/source/workflows/setup-analytics.md

Add docs for the metrics reporting endpoint

---

docs/source/tutorial/production.md

Some corrections. Sort of fixes #239. 
Scott

Update production.md Fixes (sort of) #239

---

docs/source/tutorial/data-source.md

Replace `result` with `response`.

Fix getAllLaunches Variable Mismatch

---

.github/CODEOWNERS

Currently have: @peggyrayzis @evans @jbaxleyiii @daniman @zionts
If you'd like to be removed, please holler

Add codeowners for PR reviews

---

docs/_config.yml
docs/source/platform/setup-analytics.md

These didn't get merged properly

Docs for setting up analytics agent

---

docs/source/tutorial/client.md

Remove apollo-client `alpha` reference

---

docs/source/platform/client-awareness.md

By default, Apollo Server and Apollo Client take care of most aspects of client awareness automatically, with the requirements being:
* Using recent versions of Apollo Server and Apollo Client which support client awareness automatically.
* The `name` and `version` be set on the `ApolloClient` constructor.
As currently written, the variables used in this _Advanced setup_ section have caused some to believe that those are the headers that should be used, whereas they were merely suggestions.  The _Setup_ section above should still be observed for most cases and I hope the additional clarity in this re-wording will help avoid future confusion.
cc  @michael-watson

client-awareness: Add clarity to "Advanced setup" section.

---

docs/source/platform/schema-validation.md

Fixes https://github.com/apollographql/gatsby-theme-apollo/issues/28

Use a markdown list to get inline code formatting

---

docs/source/tutorial/local-state.md

Instead of my closed pull request (I closed the original one because I have problems to do rebase after resetting from accidental merge).

Adding forgotten import statement

---

docs/source/platform/client-awareness.md

No support for client ID in engineproxy

---

docs/package-lock.json
docs/source/tutorial/data-source.md
docs/source/tutorial/introduction.md
docs/source/tutorial/production.md
docs/source/tutorial/resolvers.md
docs/source/tutorial/schema.md

General tidying and maintenance of fullstack tutorial

---

docs/source/tutorial/resolvers.md

The last paragraph of the resolvers.md file is not accurate. It states that the next section will be "...about testing your graph." However, the next section linked is "4. Run your graph in production". I would propose that the graph testing actually be put as the next section instead of how to run in production.

Last paragraph of the file not correct.

---

docs/package-lock.json
docs/source/platform/operation-safelisting.md

This guide is awesome. I found myself reading and following it to set up operation registration myself, it was a smooth read and smooth setup process. I had a few suggested tweaks to the messaging to make our term usage more clear and consistent.

Update some messaging in the op safelisting guide

---

docs/source/platform/operation-registry.md

Op-reg / safelist migration guide

---

docs/package-lock.json
docs/package.json
docs/source/index.mdx

This branch updates the docs theme and uses the new `ButtonLink` component instead of the previously used `Button`.

Upgrade theme and use ButtonLink components

---

docs/source/platform/schema-validation.mdx

Fix typo in docs

---

docs/source/platform/federation.mdx

more content under the validating changes section

---

docs/source/platform/client-awareness.md

Removed "the" before "request headers".

Fixed typo in Setup Section

---

docs/source/resources/graphql-glossary.md

This PR adds operation signature, explaining that it can be normalized or executable. Additionally we explain what normalization is

Glossary: add entry for operation signature

---

docs/static/_redirects

Helps to address https://apollographql.atlassian.net/browse/AP-1070

Add redirect for schema-validation.html

---

docs/source/tutorial/schema.md

While I understand this was already in the copy, it still might make things go more smoothly when starting out. Just a suggestion 😄

More explicit instructions

---

graph-manager-docs/source/schema-validation.mdx

I rearranged the _heck_ outta this

Edits to Schema Validation article

---

docs/static/_redirects

Fixes https://github.com/apollographql/apollo-tooling/issues/1195

Update _redirects to fix apollo-config reference

---

graph-manager-docs/components/callout-card.js
graph-manager-docs/source/index.mdx

Change the GM button to a callout card

---

docs/package-lock.json
docs/package.json
graph-manager-docs/gatsby-config.js
graph-manager-docs/package-lock.json
graph-manager-docs/package.json

This branch updates the Gatsby theme and adjusts the Graph Manager docs config to account for breaking changes.

Upgrade to next Gatsby theme major version

---

docs/source/tutorial/resolvers.md

It's getting added while coping and causing error. May be confusing for readers.

Can this line be removed?

---

docs/source/tutorial/client.mdx

Hello! I've been going through the tutorial and noticed what I think is a small spelling error.

fix spelling in the client page of the tutorial

---

studio-docs/source/org/members.mdx

My prettier also reformatted the Markdown table to be more readable in code, though there are no content changes there.

Clarify messaging about user roles access

---

docs/shared/disclaimer.mdx
docs/source/tutorial/client.mdx
docs/source/tutorial/local-state.mdx
docs/source/tutorial/mutations.mdx

Only one chapter to go after this one!
Also, much like the Queries chapter, there are changes to the tutorial codebase that need to accompany these changes.

Mutation chapter updates to follow Queries

---

studio-docs/source/github-integration.md

Without it, the wrong commit ID is sent to Studio, which cannot match it with the PR.

[GM-1608] github-integration.md: fix GitHub PR reporting with GitHub Actions

---

studio-docs/source/explorer.mdx

https://github.com/apollographql/apollo-studio-community/blob/main/CHANGELOG.md

Add new Explorer stuff to the Explorer doc in Studio docs

---

docs/README.md

This branch adds a table of all the docsets we manage and their respective GH repos

Revise the docs index GH readme

---

studio-docs/source/schema/schema-reporting-protocol.mdx

Easy navigation and easy reading for others

Fix url bug in docs

---

docs/source/tutorial/mutations.mdx

Hi, I spotted a minor indentation problem while reading the doc, so I fixed it.

Indent Login function's body

---

docs/source/tutorial/schema.md

Added scalar Float for completeness

Update schema.md added scalar Float for completeness

---

docs/source/resources/graphql-glossary.md

Easy navigation and easy reading for others

Fix broken url in docs

---

studio-docs/shared/register-federated-cli.mdx

Make link in shared content absolute

---

studio-docs/source/operation-registry.mdx

The --no-addtypename flag does not function.

Amend suggestion of removing typename

---

docs/source/devtools/editor-plugins.md

docs: Fix typo in editor-plugins

---

studio-docs/source/federated-graphs.mdx

This PR adds the demo video for the Federated graphs in Studio article.
Preview video here: https://www.youtube.com/watch?v=QaxmqfXl8HI (or on branch deploy)

Add demo video to Federated graphs in Studio article

---

docs/source/tutorial/local-state.mdx

Issue https://github.com/apollographql/apollo/issues/1144 was originally filed on the https://github.com/apollographql/apollo-client repository, so I moved it here. If there's an even better place for this issue to live, feel free to (ask me to) move it there!
Since this PR updates only the documentation, I also updated the tutorial [code](https://github.com/apollographql/fullstack-tutorial/blob/master/final/client/src/containers/action-button.tsx) over in PR https://github.com/apollographql/fullstack-tutorial/pull/213, which should probably be reviewed together with this PR.

Fix cache.modify usage in CancelTripButton component

---

docs/source/tutorial/production.md
studio-docs/source/getting-started.mdx
studio-docs/source/schema/schema-reporting.mdx

Part of apollographql/apollo-server#5157.

encourage setting APOLLO_GRAPH_ID

---

studio-docs/source/data-privacy.md

This should land on updated gateway release:
https://github.com/apollographql/federation/pull/892

Update federation API url

---

studio-docs/source/setup-analytics.mdx

Hello 👋!
Just a little PR to add a new Third-Party GL Server which support Apollo Studio trace reporting!

misc: add async-graphql to third providers

---

studio-docs/source/check-configurations.mdx

some quick fixes for some leftover apollo cli specific docs

fixup(docs): s/service:check/graph:check

---

docs/package-lock.json
docs/package.json
studio-docs/gatsby-config.js
studio-docs/package-lock.json
studio-docs/package.json

This PR bumps the docs theme version and adds some Algolia filters to the Studio docs gatsby-config to improve the search experience.

docs: add optionalFilters for Algolia

---

studio-docs/source/contracts.mdx

Show example of tag inheritance and add missing contracts error codes

Include tag inheritance example in contracts docs

---

studio-docs/components/InlineCode.js
studio-docs/source/explorer/connecting-authenticating.mdx

Add documentation for the different helpers in preflight scripts

Update preflight script docs with API

---

studio-docs/source/explorer/connecting-authenticating.mdx

Today we started exposing the crypto-js package in preflight scripts as `explorer.CryptoJS`
Sorry @StephenBarlow, i'm not sure how to word this one so I might be leaning on you a bit hahaha

Update  preflight script docs with new crypto-js api

---

studio-docs/source/explorer/embed-explorer.mdx

currently CORS erroring on the endpoint at /

update endpoint for fullstack tutorial to /graphql
