apollographql/apollo

docs/package-lock.json
docs/package.json

The default syntax highlighting provided by Hexo uses highlight.js.  While there are a number of great syntax highlights provided by highlight.js, some of the more important ones to the Apollo project: `graphql`, `typescript`, and `jsx` are notably missing.
This uses the `hexo-prism-plus` plugin for Hexo, along with some upstream configuration to `apollo-hexo-config`[0] and `meteor-theme-hexo` (previously named `hexo-theme-meteor`)[1].  See refs for more information!
**The Netlify preview for this PR should be checked prior to merging!**
:crossed_fingers:
[0] https://github.com/apollographql/apollo-hexo-config/commit/547107b0
[1] https://github.com/meteor/meteor-theme-hexo/pull/61

docs: Add `hexo-prism-plus` to enable Prism syntax highlighting.

---

docs/source/index.md

this PR fixes a broken link to the `Fundamentals` guide

fix image link for fundamentals guide

---

docs/source/guides/testing-react-components.md

This is editorial work for https://github.com/apollographql/apollo/pull/164.  It also targets that PR and will merge into it.
The changes I've introduced here try to remove the subject of "you".  This is a pattern which we've tried to perpetuate in other portions of the documentation.
In my experience this has generally made the content more succinct (i.e. shorter), but also simplifies translation in some languages and makes the content more easily digestible for those who might be less proficient by removing the extra, unnecessary subject.
I have some concerns about using the [`awwait`](https://npm.im/awwait), since it's basically a full npm module that does:
await (new Promise(r => setTimeout(r, 0)))
I think we can probably accomplish the same testing without this module by using …

Editorial for https://github.com/apollographql/apollo/pull/164.

---

docs/_config.yml
docs/package-lock.json
docs/source/guides/testing-react-apollo.md
docs/source/guides/testing-react-components.md

This is a guide specifically for testing React Apollo. Based off of @excitement-engineer's (great) original work [in this PR](https://github.com/apollographql/apollo-client/pull/3309).
**A few notes:**
- I'm keeping this separate from server testing, since combined I think they'll be too long. **I'm open to discussion on this, though**.
- I added the guide here rather than React Apollo's docs, since I feel like we have a good set of `guides` here, and would hate for this to be missing. I also feel like the view logic may transfer to other UI integrations, but I don't have a lot of insight into that.
- I went with using `wait(0)` instead of refactoring and counting renders like some other exmples do, for simplicity. I wanted to lower the barrier of entry for testing as much as possible.
- …

React Apollo Testing

---

docs/package-lock.json
docs/package.json

By virtue of a relatively simple `hexo-browsersync` package[0], which
implements BrowserSync[1] in Hexo, this change brings support for automatically
reloading the browser when the source content has changed.
No more pressing "Reload" in order to see the changes to the Markdown source
when working on documentation! :tada:
[0]: https://npm.im/hexo-browsersync
[1]: https://www.browsersync.io

docs: Add browser auto-reloading on source content changes.

---

docs/source/guides/performance.md

Most importantly, this fixes the structure of the headings in this document, which were previously appearing as such:
After this change, it will appear more correctly as:

Adjustments to the Performance/CDN page.

---

README.md
docs/source/fundamentals/benefits.md
docs/source/fundamentals/platform.md
docs/source/guides/access-control.md
docs/source/guides/security.md

This updates all blog URLs in the documentation to use blog.apollographql.com
as the domain, rather than dev-blog.apollodata.com.

docs: Update blog URLs to reference blog.apollographql.com.

---

docs/source/guides/access-control.md

In the first example, the author used `req.headers.authorization` to store/retrieve the authentication token, but in the second code snippet, `req.headers.authentication` was used

Change `authentication` to `authorization`

---

docs/source/guides/file-uploads.md

The file uploads guide shows how to install the `apollo-upload-client` package, and provides React Apollo based examples showing how to submit file uploads. The listed examples will not work however, unless the `apollo-upload-client` package is properly integrated into Apollo Client. The changes in this commit show how to use `createUploadLink` with Apollo Client (to enable `apollo-upload-client`), and note the fact that `apollo-upload-client` will not work with Apollo Boost.
Thanks!

Mention `createUploadLink` in client side upload docs

---

docs/source/guides/testing-react-components.md

I was testing my application and had to look in a specific part of documentation to understand that `graphQLErrors` are just taken from the result. This might help a few people like in https://github.com/apollographql/react-apollo/issues/1127.
Using `error` key on the mock will only result in a `networkError` define. This fix explains how to define GraphQL errors which might not be explicit when a beginner is not used to it.

Explain how to mock GraphQL errors

---

docs/source/tutorial/production.md

This is the first draft for the `Run your graph in production` section.
The content here covers:
* Deploying your graph API to Now
* Publishing your schema to Engine via the Apollo CLI
* How to hook up Apollo Server with Engine for performance monitoring
The content here doesn't cover:
* Operation Registry
* VS code set up

Run your graph in production

---

docs/source/tutorial/resolvers.md

The function accepts the following arguments: parent, args, context, info
In the next paragraph, the 'parent' argument is explained but written as 'root' instead of 'parent'
You could also add somewhere in the sentence that the parent is root value passed from server.

Updated resolvers.md, typo/inconsistent naming

---

docs/source/references/apollo-engine.md

Moved this content over directly from the Engine docs.
Once landed, I'll remove the content from the Engine docs and set up a redirect.

Add our GDPR guide to the Platform docs

---

docs/source/tutorial/data-source.md

Hi there,
I found that many of the variable names were shortened to a single letter or were just shortened versions of a real word. Although this may be a common practice in many codebases (though I disagree with it personally but that's a separate discussion), I feel that tutorial documentation benefits from as much clarity as is practical.
In my PR I have modified some of the variable names which I hope improves the clarity of this page.
I have also made a small code change from `response && response.length` to `Array.isArray(response)` as I believe this again improves the clarity of the tutorial.
I understand many of these choices are very subjective so please feel free to comment and suggest changes as you see fit!
And finally, I hope you are all enjoying yourselves during these …

Improve tutorial docs (data-source page)

---

docs/source/tutorial/resolvers.md

This pull request updates the way we use constructor, to get rid of the deprecation warning.

Change Buffor constructors to `from` method

---

docs/source/tutorial/client.md

The formatting of [this article](https://www.apollographql.com/docs/tutorial/client.html) was broken:

Fix Markdown formatting in client.md

---

docs/source/platform/operation-registry.md

Subscription support is enabled by default in Apollo Server 2.x and provided by a separate server which does not utilize Apollo Server 2.x's primary request pipeline.  Currently, no plugin, including the operation registry plugin, is able to interact with the request pipeline, making it a necessity to disable the subscriptions features unless operation registry enforcement is not desired.
In the future, the subscription support will have its request pipeline unified with that of the main request pipeline, thus enabling plugin support and permitting the the operation registry to work with subscriptions in the same way that it works with regular GraphQL requests.

operation-registry: Add instructions on how to disable the subscription server.

---

docs/source/tutorial/client.md

The modified header has the exact same `id` as the one above, likely a leftover from copy-pasting =)

Fix duplicated heading id in the docs.

---

docs/source/tutorial/local-state.md
docs/source/tutorial/mutations.md

Initializers are no longer part of the AC local state API. We're now recommending that people use `cache.writeData` directly, since it's already part of the Apollo Cache API and is more flexible.

Replace local state `initializers` with `cache.writeData`

---

docs/source/platform/operation-registry.md

The Apollo Server operation registry plugin — available for Apollo Engine
Team and Enterprise users, will SOON (in the next day or so) support passing a predicate function rather than a boolean on the `forbidUnregisteredOperations` parameter.
This new parameter can be used to selectively enforce the safe-listing
depending on contextual differences — for example, the presence of a header.
This documentation adds the implementation details for that new feature
along with an example of how to utilize it.

(op-reg) Update for `forbidUnregisteredOperations` predicate function support.

---

docs/source/platform/schema-validation.md

This PR adds documentation for 3 new flags for the `service:check` CLI command:
* validationPeriod
* queryCountThreshold
* queryCountThresholdPercentage
Also removes a broken link to performance metrics `./performance.html`
This PR is best read by commits, since the second commit is strictly prettier re-formatting the markdown file.

Update `service:check` docs with new flags

---

docs/source/tutorial/data-source.md

We define the response variable but then pass in an undefined "result" variable

Pass in the correct variable name

---

docs/source/tutorial/introduction.md

Note: I noticed that the old URL `https://www.apollographql.com/slack` redirects to the Spectrum community, but I'm not sure if it does more than redirecting like analysis or something like that, So, please take that on consideration while reviewing the PR.

Update Apollo community from Slack to Spectrum.

---

docs/source/platform/client-awareness.md

An "application programming interface" need not be capitalized in its full form, but I believe API should remain capitalized.
With all due respect to SCUBA, I'm not willing to let every form initialism land in the dictionary in lower-case.

client-awareness: Change many uses of "api" to "API".

---

docs/source/tutorial/data-source.md

The doc highlight can lead to user being confuse about what needed to be added in `src/index.js`
I do agree that Highlighting most of the box seems weird and remove the purpose of the highlight in the first place. But just highlighting a part of it is counter intuitive and can lead to the user being confuse.

Fix confusing highlight on data-source tutorial

---

docs/package-lock.json
docs/source/platform/schema-validation.md

To enable all of the links in the engine frontend, we include all of the changes in the list.
This PR also provides more context around why a change fails the `service:check` command.

Add compatible changes and update descriptions of breaking changes

---

docs/package.json

This branch removes the `--prefix-paths` option from `gatsby develop` in our NPM start script for the docs.

Remove --prefix-paths in development

---

docs/source/platform/schema-registry.md

reorient intro to focus on benefits of a schema registry. evict most of the validation stuff, since we now have a separate section for that.

updated intro

---

docs/source/platform/operation-registry.md

This PR adds documentation that explains the new `dryRun` option for the operation registry plugin.
For reference: https://github.com/apollographql/apollo-platform-commercial/pull/71

Registry plugin `dryRun` documentation

---

netlify.toml

This branch fixes Netlify redirects for this repo by adding an additional deploy command that moves the `_redirects` file to the public directory where it belongs. This should fix clicking on deploy preview links and cause all redirects to work again.

Move the _redirects file to the public dir

---

docs/source/references/engine-proxy.md

This page was moved shortly after it was created so a redirect doesn't seem necessary, but updating the also recently-added links to the new location seems important!

Fix link for "Setup Analytics" which was moved.

---

docs/source/platform/operation-registry.md

Currently, the operation registry does not support any schema tags besides the default schema tag of `current`.  Users can still use the operation registry, but they should make sure that they also register their schema to the `current` tag.

op-reg: Add notes about schema tag limitations.

---

docs/source/platform/operation-registry.md

This has caused some confusion. I didn't understand that the operation registry is a bucket filled with valid operation hashes that grew forever. I thought we were going to be authorizing specific clients and versions to specific operations, that is not the case.

[WIP] Describe permanence of operation registry

---

docs/gatsby-config.js
docs/source/platform/operation-safelisting.md
docs/static/_redirects

This is a spin-off of thoughts from #354.
We've been slowly transiting the Platform docs articles to describe workflows as opposed to features/fixtures; i.e. the "why" instead of the "what". Renaming this article to "Operation Safelisting" as opposed "Operation Registry" is in line with that plan, as the safelisting is the reason why one would opt into using the operation registry today.
Platform docs articles:
We may want to consider having multiple articles to represent the operation registry in the future, just like we have two to represent the schema registry ([Tracking your GraphQL schema](https://www.apollographql.com/docs/platform/schema-registry) and [Validating schema changes](https://www.apollographql.com/docs/platform/schema-validation)). We should do that when the time comes.

Rename operation-registry to operation-safelisting

---

docs/gatsby-config.js
docs/source/platform/operation-registry.md
docs/static/_redirects

Reverts apollographql/apollo#455
As has always been our policy for moving documentation around, this should have a redirect setup for it to preserve existing links.  I'm reverting it because that should be done as part of the rename and currently, existing links would be broken because of this.  
Additionally, I do think we should discuss it first.

Revert "Rename operation-registry to operation-safelisting"

---

docs/source/tutorial/introduction.md

The tutorial uses `async`/`await` syntax which was introduced in Node 7.6.0

Correct minimum node and npm versions

---

docs/source/platform/operation-registry.md

(Note: can merge after https://github.com/apollographql/apollo-tooling/pull/1307 is released. update: released)
This PR adds 2 optional sub-steps in the setup flow to demonstrate how to configure the schema tag for the operation registry plugin and the cli  
It also removes the "Only the default schema tag (`current`) is supported." section from the "Limitations" section

Document how to configure schemaTag in operation registry plugin - AP-468

---

docs/source/tutorial/resolvers.md

`missionPatch`'s type in the schema must have accidentally been changed from `String` to `PatchSize` when a resolver was added.
This causes a fairly difficult to debug error in the Client UI while working through the tutorial. (at least for graphQL newbies like me 😛 )

Change missionPatch type to String

---

docs/source/platform/operation-registry.md

It wasn't entirely clear that it's safe to update the plugin. This updates the documentation to include more information about the updates and attempts to clarify that updating the plugin can happen immediately

op-reg: update summary of changes to expand on tags

---

docs/source/platform/operation-registry.md
docs/source/platform/operation-registry.mdx

Nothing here should change much, but we should verify that users don't
need to do anything to use the operation registry, and if they do, then
we should document those.

Federation: Update operation registry docs [AP-587]

---

docs/source/platform/operation-registry.mdx

There are a couple broken headings in the operation registry docs, this adds missing spaces so the MD is interpreted correctly.

Fix headings in operation-registry docs

---

docs/source/platform/schema-registry.mdx

Specifically, this PR should update the `schema-registry.mdx` file to
illustrate how to use `service:push` with a `--serviceName` flag for
federation and also indicate that it should always be done after a
deployment fully rolls out.

[WIP] Federation: Stub PR to update `service:push`

---

docs/source/references/apollo-config.md

Right now, the Apollo CLI and tooling does not FULLY support multiple projects being configured with the same file. Even if they consists of a single client and a single service project.
With some commands, there may be issues that are unaccounted for and not tested properly. I propose we change the documentation here to reflect that more clearly.
An example of this confusion and technical issues is [here](https://github.com/apollographql/apollo-tooling/issues/792#issuecomment-455625551)

Note that apollo.config.js can only be used on a single project

---

docs/source/tutorial/production.md

In #444 the section on deploying the app was removed, but the section on signing up for Zeit was missed. This means people following the tutorial will create an account for no reason. This PR removes that reference.

Remove all references to Zeit Now

---

docs/source/intro/benefits.md
docs/source/tutorial/client.md
docs/source/tutorial/local-state.md
docs/source/tutorial/mutations.md
docs/source/tutorial/queries.md

This PR updates the tutorial and platform parts of the docs to use Hooks, instead of render prop components. This work should not be merged until RA 3 is launched, and the following have also been merged:
- https://github.com/apollographql/fullstack-tutorial/pull/93
- https://github.com/apollographql/apollo-client/pull/5119

Hooks conversion

---

docs/source/tutorial/resolvers.md

Line 266 says that "we know how to add resolvers on types other than `Query` and `Mutation`", but the tutorial hasn't touched Mutation resolvers so far. The Mutation resolvers are in line 332
I highly suspect the author meant to write "Mission" as that was the last type visited in the tutorial

Typo fix: `Mutation` instead of `Mission` in resolvers.md

---

docs/gatsby-config.js
docs/source/index.mdx
docs/source/platform/graph-manager-overview.md
docs/source/references/apollo-engine.md
docs/source/references/engine-proxy.md
docs/source/references/graph-manager-data-privacy.md
docs/static/_redirects

This change seeks to better convey the components and purpose of the Apollo platform on the documentation homepage.
In service of that change, this PR also adds an overview for Graph Manager, which currently doesn't have an obvious first-place-to-go in the docs. The overview's content is pulled partly from the "Engine guide", which is being renamed to "Graph Manager Data Privacy and Compliance" to better reflect its focused scope.

Content edit for docs landing page and Graph Manager overview

---

docs/source/intro/benefits.md
docs/source/old/performance.md
docs/source/platform/client-awareness.md
docs/source/platform/editor-plugins.md
docs/source/platform/federation.mdx
docs/source/platform/graph-manager-overview.md
docs/source/platform/integrations.md
docs/source/platform/operation-registry.mdx
docs/source/platform/performance.md
docs/source/platform/schema-registry.mdx
docs/source/platform/schema-validation.mdx
docs/source/references/apollo-config.md
docs/source/references/engine-proxy.md
docs/source/references/setup-analytics.md
docs/source/resources/faq.md
docs/source/resources/graphql-glossary.md
docs/source/tutorial/client.md
docs/source/tutorial/introduction.md
docs/source/tutorial/production.md

Ignores Engine-proxy-related articles, which should remain as-is due to deprecated status

Rename instances of Engine to Graph Manager

---

docs/source/tutorial/client.md

Sample code does not have trailing semi-colons which is inconsistent with other examples.

Inconsistent use of semi-colons

---

graph-manager-docs/source/federation.mdx

In some environments where outbound traffic is restricted, it may be necessary to configure the Apollo Gateway and Apollo Server to route their outgoing traffic through a proxy (corporate, or otherwise).  These instructions now exist within the Apollo Server documentation (https://www.apollographql.com/docs/apollo-server/proxy-configuration/) an this adds a reference accordingly.
Follows-up: https://github.com/apollographql/apollo-server/pull/3332 (on the Apollo Server repository)

Add reference to Apollo Server proxy configuration documentation.

---

graph-manager-docs/source/federation.mdx

While it is possible for the `ENGINE_API_KEY` to be used, it's also possible to leverage the existing pattern supported by Apollo Server 2.x where the `engine` property can be set to the key, or the more customizable [`EngineReportingOptions`](https://www.apollographql.com/docs/apollo-server/api/apollo-server/#enginereportingoptions).  
Put another way, Apollo Gateway is automatically passed the options from Apollo Server's `engine` options, when they are set.

Clarify options for setting of the Apollo Gateway API key

---

graph-manager-docs/source/operation-registry.mdx

This add documentation for the new lifecycle hooks
* willUpdateManifest(newManifest?: OperationManifest, oldManifest?:
OperationManifest) => OperationManifest
* Run with newManfifest=resultFromGCS when new manifest returned
from GCS(polled every minute)
* Run with newManifest=undefined if the manifest is not
retrieved from gcs on startup
* oldManifest set to the existing manifest if one is present
* onUnregisteredOperation(requestContext)
* run when an operation is not found in the safelist
* onForbiddenOperation(requestContext)
* run when an operation is not in the safelist and
user-defined override
(forbidUnregisteredOperations(requestContext) =>
boolean) doesn't accept the operation

op-reg: document lifecycle hooks [AP-562]

---

CODE-OF-CONDUCT.md
CONTRIBUTING.md

CONTRIBUTING.md seemed to use non-Unix newline conventions, so this resolves that in addition to pointing folks to Spectrum instead of Slack

Replace Slack with Spectrum, UNIX-ify CONTRIBUTING

---

docs/source/tutorial/resolvers.md

I'm not sure if this is trying to say that we cloned the entire repo in the previous section, or just that we copied code into the `src/utils.js` file in the previous section, but either way that isn't true. We cloned the repo several sections ago, and we didn't have to explicitly copy the `utils.js` file ever. Seems more concise to just remove it.

Remove vestigial(?) reference to previous section

---

docs/source/tutorial/queries.mdx

In a tutorial of `6. Fetch data with queries`, a file type is written `jsx` instead of `tsx`.  
The file name is `src/pages/launch.tsx`, but that file type is `JavaScript`.
I think it should be fixed.
[![Screenshot from Gyazo](https://gyazo.com/9edd8937f8d5f00f0edbbc47481bb3eb/raw)](https://gyazo.com/9edd8937f8d5f00f0edbbc47481bb3eb)
[![Screenshot from Gyazo](https://gyazo.com/2ff87d9d1ff8be46993f25e14a60a40d/raw)](https://gyazo.com/2ff87d9d1ff8be46993f25e14a60a40d)
Thank you.

A incorrect file type fixed(small issue)

---

docs/source/tutorial/client.mdx
docs/source/tutorial/data-source.md
docs/source/tutorial/production.md
docs/source/tutorial/resolvers.md

I noticed that some of the tutorial code block titles were inconsistent, so here's a small PR that fixes those inconsistencies. Related to [this PR](https://github.com/apollographql/gatsby-theme-apollo/pull/115).
Before:
After:

Fix titles in tutorial code blocks.

---

docs/source/devtools/apollo-config.md
docs/source/devtools/editor-plugins.md
graph-manager-docs/source/managed-federation/advanced-topics.mdx
graph-manager-docs/source/operation-registry.mdx
graph-manager-docs/source/schema-registry.mdx
graph-manager-docs/source/schema-validation.mdx

This is to support a change to the command line tool to prefer using
--variant to --tag and deprecate the latter. Please see https://github.com/apollographql/apollo-tooling/pull/1849 for reference! We should correspond timing of the two :)

Change --tag references to --variant for commands

---

docs/source/tutorial/client.mdx
docs/source/tutorial/local-state.mdx
docs/source/tutorial/mutations.mdx
docs/source/tutorial/queries.mdx

Quick win updates covering simple things like using `@apollo/client` instead of `apollo-client`, `@apollo/react-hooks`, `graphql-tag`, etc. This PR does not cover updating content to match the AC3 `fullstack-tutorial` updates made in https://github.com/apollographql/fullstack-tutorial/pull/118. That work is outstanding but is something we'll want to tackle, as the web content of the tutorial is recommending practices we no longer advocate with AC3 (e.g. we have a new pagination approach, we're deprecating local resolvers in favor of type/field policies, etc.).

Initial AC3 updates

---

docs/source/devtools/cli.md
docs/source/tutorial/production.md
studio-docs/source/client-awareness.md
studio-docs/source/data-privacy.md
studio-docs/source/getting-started.mdx
studio-docs/source/managed-federation/advanced-topics.mdx
studio-docs/source/operation-registry.mdx
studio-docs/source/performance.md
studio-docs/source/schema/schema-reporting-protocol.mdx
studio-docs/source/schema/schema-reporting.mdx
studio-docs/source/setup-analytics.mdx

Update AS configuration docs to use the new v2.18 plugin API (or just to use
APOLLO_SCHEMA_REPORTING=true rather than code to turn on schema reporting).

Remove more references to engine and graph manager

---

studio-docs/source/data-privacy.md
studio-docs/source/getting-started.mdx
studio-docs/source/schema-checks.mdx
studio-docs/source/schema/schema-reporting.mdx

Different versions of Apollo Server and the Apollo CLI send data to
different URLs. This adds a section into the "data privacy" document to
indicate which versions of each piece of open source technology send
which data to which domains. This does not include anything about which
data is sent using the Apollo CLI.
In particular, this comes along with an effort that David Glasser is
taking to de-engine-ify our open source technology, and as such update
our domains to use generic *.api.apollographql.com domains. These
changes should not be released until corresponding versions of the CLI
and Apollo Server have landed.

Add docs to identify which URLs are used from CLI/AS

---

studio-docs/source/schema-checks.mdx

Our GraphQL API has new description change codes, and our history page will link to the checks docs page for each of those new change codes shortly.
This PR adds those new change codes to the checks docs page. Note that unlike other change codes, `CHANGE` in description change codes may refer to an addition, removal, or update (for other change codes, `CHANGE` refers to just an update).

docs: Add new description change codes to schema-checks.mdx

---

docs/source/tutorial/mutation-resolvers.md

This mutation query without a subfield results in the following error:     
"errors": [
{
"message": "Field \"login\" of type \"User!\" must have a selection of subfields. Did you mean \"login { ... }\"?"
In order to prevent this error, I added two subfields. I maintain use of the original token string and made minor edits to then isolate the token string from the mutation output and continue with the original flow of the tutorial.

Add subfields to LoginUser mutation to avoid error

---

studio-docs/gatsby-config.js
studio-docs/source/data-privacy.md
studio-docs/source/explorer.mdx
studio-docs/source/getting-started.mdx
studio-docs/source/index.mdx
studio-docs/source/schema/registry.mdx

Turns out the https://studio.apollographql.com/explorer link is now broken and I didn't realize it, and so I thought I'd take the opportunity to replace that broken link with a dedicated doc on the Explorer that I think we've needed for a while.
I'm not sure what the right place to put this doc is in the structure. Current place seems neither great nor awful to me 🤷 
This document:
- goes over all the basics of the Explorer (editor, query building, search –– mostly lifted from the announcement post)
- goes over setup (CORS), authentication, and distribution
- most importantly: adds a feature list for everything we've added so far (most of which is unique to the Explorer among other GraphQL querying tools), adds the list in a way that we can expand upon easily

Add a doc for the Explorer to the Studio docs

---

docs/source/tutorial/resolvers.md

There is no `getLaunchIDsByUser ` in the  `final/server/src/datasources/user.js`.
Just a typo.

fix typo in resolver.md

---

docs/source/tutorial/production.md

Typo under Create your first graph in section 5 of the tutorial 
> - apollo/docs/source/tutorial/production.md

Fix typo under tutorials create your first graph

---

studio-docs/shared/obtain-graph-api-key.mdx
studio-docs/shared/obtain-personal-api-key.mdx
studio-docs/source/api-keys.mdx
studio-docs/source/org/graphs.mdx
studio-docs/source/org/members.mdx
studio-docs/source/org/organizations.mdx

Document the upcoming Studio feature to add support for graph roles & protected variants, outlined here: https://github.com/apollographql/apollo-studio-community/blob/main/preview-docs/GraphRoles.md.
We'll want to hold off on merging this PR until the feature ships, but I figured it would be good to stage and prepare all the same.

studio docs: graph roles & protected variants

---

docs/source/tutorial/mutation-resolvers.md

I was a bit confused when I got to the part in chapter 4 (Write query resolvers) that defines the context object without mention of dataSources, even though we expected dataSources to be in the context argument in the query resolvers. Had to check the apollo-server documentation to clear it up. This just adds a quick clarification point to that end. Thanks!

Clarify relationship between dataSources and context

---

docs/source/intro/benefits.md
docs/source/intro/platform.md
docs/source/tutorial/client.mdx
docs/source/tutorial/production.md
studio-docs/source/check-configurations.mdx
studio-docs/source/daily-reports.md
studio-docs/source/datadog-integration.md
studio-docs/source/federated-graphs.mdx
studio-docs/source/getting-started.mdx
studio-docs/source/notification-setup.md
studio-docs/source/org/graphs.mdx
studio-docs/source/performance-alerts.md
studio-docs/source/schema-change-integration.md
studio-docs/source/schema-checks.mdx
studio-docs/source/setup-analytics.mdx

In #1134 I added the Federated graphs in Studio article, but I forgot to include alt tags on the screenshots. Accessibility is very important. 🙏 This PR remedies that oversight.
Also fixes the image tags in several files where they were not self closing, or forgot the trailing slash. ✨

Add alt tags to Federated graphs in Studio article

---

studio-docs/source/explorer.mdx

We no longer support using JSON for setting or storing request headers.

Changes to request headers in Explorer

---

README.md

Replacing the reference to spectrum.chat with the new [Apollo GraphQL Community forums](https://community.apollographql.com/)

(docs) Replace spectrum reference with Apollo GraphQL Community link

---

docs/source/tutorial/data-source.md

The old URL led to a 404, so I googled the title and this is the link that I'm pretty sure replaces it.

Update data-source.md blog link

---

studio-docs/gatsby-config.js
studio-docs/source/audit-log.md

We will probably want to add a table to represent what the material events we add to the log are, but I think this is a fine start.

Add a Studio docs article for the Audit Log feature

---

docs/static/_redirects
studio-docs/static/_redirects

This branch removes the `/ /docs` and `/ /docs/studio` redirects, previously used to send our root-level deploy preview links to the right place when clicked on in the Netlify GitHub check. Unfortunately, it seems like these redirects are causing issues with Netlify when we use split tests, causing users to be redirected from our home page to the docs.
This change is an attempt to fix that, at the known cost of having to manually add "/docs" or "/docs/studio" to the end of deploy previews when previewing changes.
I'm going to investigate options to conditionally add a root redirect to deploy previews **only** but we want to unblock split testing first, so I made this a separate PR.
@netlify /docs

Remove root redirect

---

netlify.toml

This branch tells netlify to deploy our docs deploy previews at / instead of nesting them in the location we expect them to be in prod.

Deploy deploy previews at /

---

docs/gatsby-config.js
docs/source/resources/elastic-license-v2-faq.md
docs/source/resources/faq.md

We're moving the Federation 2 libraries and gateway, the Rover composition add-on, and Workbench to the Elastic License 2.0 (ELv2). This FAQ addresses common questions about ELv2.

Add Apollo FAQ for Elastic License v2

---

studio-docs/source/build-status-notification.md

Adding the `buildSucceeded: boolean` property to the ResponseShape interface used with the build status notification webhook

(docs) Add buildSucceeded property to build status notification event

---

studio-docs/source/contracts.mdx

Paired with @david-castaneda @pcarrier @caydie-tran 
This PR updates the documentation for new contracts behavior.
Specifically, when filtering types/fields using include filters, we won't mark an object/interface type as `@inaccessible` if it doesn't match an include filter (unlike other supported schema elements).
See https://github.com/mdg-private/gravity-planning/issues/576

contracts: Updated docs for new contracts behavior

---

studio-docs/source/contracts.mdx

Fix the @tag definition in the contracts example by removing the `|` before `FIELD_DEFINITION`
I used this formatter but not sure if theres a recommended way to format it:
https://jsonformatter.org/graphql-formatter

contracts: Fix `@tag` definition

---

studio-docs/source/contracts.mdx

Fixes the line numbers that are highlighted in the GraphQL markdown example in contracts docs

contracts: Fix example markdown highlighted area

---

docs/package-lock.json
docs/package.json
studio-docs/package-lock.json
studio-docs/package.json

This PR bumps Gatsby to v3 and the docs theme to the corresponding (experimental) version that supports this upgrade.

Docs: Bump to Gatsby v3

---

studio-docs/source/operation-registry.mdx

The `apollo-server-plugin-operation-registry` package is now being published under the name `@apollo/server-plugin-operation-registry`.
The related docs / migration guide that existed for the `0.2.x` versions could probably use a refresher (or maybe removal, though a quick perusal of npm downloads per version shows that some people are still using _very_ old versions of the plugin and would qualify for the migration guide).
cc @StephenBarlow @rkoron007

Update references to op reg plugin

---

studio-docs/source/data-privacy.md

These were old things included in responses from graphs to the old engineproxy and aren't used these days.

data-privacy: remove reference to old extensions
